CREATE DATABASE IF NOT EXISTS auth;

USE auth;

CREATE TABLE User(
	idUser INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(31) NOT NULL,
	surname VARCHAR(31) NOT NULL,
	email VARCHAR(127) NOT NULL UNIQUE,
	password_hash VARCHAR(257) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(), 
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() 
);

CREATE TABLE access_log(
	idLogAccess INT PRIMARY KEY AUTO_INCREMENT DEFAULT NULL,
	fk_account INT DEFAULT NULL,
	ip VARCHAR(127) DEFAULT NULL,
	user_agent VARCHAR(511) DEFAULT NULL,
	email VARCHAR(127) DEFAULT NULL,
	operation VARCHAR(127) NOT NULL DEFAULT "attempted_login",
	logged_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	FOREIGN KEY (fk_account) REFERENCES User(idUser)
);

CREATE TABLE session(
	idSession INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	sid VARCHAR(511) NOT NULL UNIQUE,
	ttl TIMESTAMP DEFAULT TIMESTAMPADD(DAY, 7, CURRENT_TIMESTAMP),	
	fk_user INT NOT NULL,
	FOREIGN KEY (fk_user) REFERENCES user(idUser) ON DELETE CASCADE
);



